import { Injectable } from '@angular/core';
import { Country } from '../models/country';
import { State } from '../models/state';

@Injectable()
export class CountryStateService {

  constructor() { }

  getCountries() {
    return [
      new Country('USA'),
      new Country('Canada'),
      new Country('India'),
      new Country('Australia')
    ];
  }

  getStates() {
    return [
      new State('USA', 'Alabama'),
      new State('USA', 'Alaska'),
      new State('USA', 'Arizona'),
      new State('USA', 'Arkansas'),
      new State('USA', 'California'),
      new State('USA', 'Colorado'),
      new State('USA', 'Connecticut'),
      new State('USA', 'Delaware'),
      new State('USA', 'District of Columbia'),
      new State('USA', 'Florida'),
      new State('USA', 'Georgia'),
      new State('USA', 'Hawaii'),
      new State('USA', 'Idaho'),
      new State('USA', 'Illinois'),
      new State('USA', 'Indiana'),
      new State('USA', 'Iowa'),
      new State('USA', 'Kansas'),
      new State('USA', 'Kentucky'),
      new State('USA', 'Louisiana'),
      new State('USA', 'Maine'),
      new State('USA', 'Maryland'),
      new State('USA', 'Massachusetts'),
      new State('USA', 'Michigan'),
      new State('USA', 'Minnesota'),
      new State('USA', 'Mississippi'),
      new State('USA', 'Missouri'),
      new State('USA', 'Montana'),
      new State('USA', 'Nebraska'),
      new State('USA', 'Nevada'),
      new State('USA', 'New Hampshire'),
      new State('USA', 'New Jersey'),
      new State('USA', 'New Mexico'),
      new State('USA', 'New York'),
      new State('USA', 'North Carolina'),
      new State('USA', 'North Dakota'),
      new State('USA', 'Ohio'),
      new State('USA', 'Oklahoma'),
      new State('USA', 'Oregon'),
      new State('USA', 'Pennsylvania'),
      new State('USA', 'Rhode Island'),
      new State('USA', 'South Carolina'),
      new State('USA', 'South Dakota'),
      new State('USA', 'Tennessee'),
      new State('USA', 'Texas'),
      new State('USA', 'Utah'),
      new State('USA', 'Vermont'),
      new State('USA', 'Virginia'),
      new State('USA', 'Washington'),
      new State('USA', 'West Virginia'),
      new State('USA', 'Wisconsin'),
      new State('USA', 'Wyoming'),

      new State('Canada', 'Alberta'),
      new State('Canada', 'British Columbia'),
      new State('Canada', 'Manitoba'),
      new State('Canada', 'New Brunswick'),
      new State('Canada', 'Newfoundland'),
      new State('Canada', 'Northwest Territories'),
      new State('Canada', 'Nova Scotia'),
      new State('Canada', 'Nunavut'),

      new State('India', 'Andaman and Nicobar Islands'),
      new State('India', 'Andhra Pradesh'),
      new State('India', 'Arunachal Pradesh'),
      new State('India', 'Assam|Bihar'),
      new State('India', 'Chandigarh'),
      new State('India', 'Chhattisgarh'),
      new State('India', 'Dadra and Nagar Haveli'),
      new State('India', 'Daman and Diu'),
      new State('India', 'Goa'),
      new State('India', 'Gujarat'),
      new State('India', 'Haryana'),
      new State('India', 'Himachal Pradesh'),
      new State('India', 'Jammu and Kashmir'),
      new State('India', 'Jharkhand'),
      new State('India', 'Karnataka'),
      new State('India', 'Kerala'),
      new State('India', 'Lakshadweep'),
      new State('India', 'Madhya Pradesh'),
      new State('India', 'Maharashtra'),
      new State('India', 'Manipur'),
      new State('India', 'Meghalaya'),
      new State('India', 'Mizoram'),
      new State('India', 'Nagaland'),
      new State('India', 'Orissa'),
      new State('India', 'Pondicherry'),
      new State('India', 'Punjab'),
      new State('India', 'Rajasthan'),
      new State('India', 'Sikkim'),
      new State('India', 'Tamil Nadu'),
      new State('India', 'Tripura'),
      new State('India', 'Uttar Pradesh'),
      new State('India', 'Uttaranchal'),
      new State('India', 'West Bengal'),


      new State('Australia', 'Australian Capital Territory'),
      new State('Australia', 'New South Wales'),
      new State('Australia', 'Northern Territory'),
      new State('Australia', 'Queensland'),
      new State('Australia', 'South Australia'),
      new State('Australia', 'Tasmania'),
      new State('Australia', 'Victoria'),
      new State('Australia', 'Western Australia'),

      //////////////////

      new State('Cambodia', 'Banteay Mean Chey'),
      new State('Cambodia', 'Batdambang'),
      new State('Cambodia', 'Kampong Cham'),
      new State('Cambodia', 'Kampong Chhnang'),
      new State('Cambodia', 'Kampong Spoe'),
      new State('Cambodia', 'Kampong Thum'),
      new State('Cambodia', 'Kampot'),
      new State('Cambodia', 'Kandal'),
      new State('Cambodia', 'Koh Kong'),
      new State('Cambodia', 'Kandal'),
      new State('Cambodia', 'Koh Kong'),
      new State('Cambodia', 'Kracheh'),
      new State('Cambodia', 'Mondol Kiri'),
      new State('Cambodia', 'Otdar Mean Chey'),
      new State('Cambodia', 'Pouthisat'),
      new State('Cambodia', 'Preah Vihear'),
      new State('Cambodia', 'Prey Veng'),
      new State('Cambodia', 'Rotanakir'),
      new State('Cambodia', 'Siem Reab'),
      new State('Cambodia', 'Stoeng Treng'),
      new State('Cambodia', 'Svay Rieng'),
      new State('Cambodia', 'Takao'),
      new State('Cambodia', 'Keb'),
      new State('Cambodia', 'Pailin'),
      new State('Cambodia', 'Phnom Penh'),
      new State('Cambodia', 'Preah Seihanu'),
      
      new State('Cameroon', 'Adamaoua'),
      new State('Cameroon', 'Centre'),
      new State('Cameroon', 'Est'),
      new State('Cameroon', 'Extreme-Nord'),
      new State('Cameroon', 'Littoral'),
      new State('Cameroon', 'Nord'),
      new State('Cameroon', 'Nord-Ouest'),
      new State('Cameroon', 'Ouest'),
      new State('Cameroon', 'Sud'),
      new State('Cameroon', 'Sud-Quest'),
      
      new State('Central African Republic', 'Bamingui-Bangoran'),
      new State('Central African Republic', 'Bangui'),
      new State('Central African Republic', 'Basse-Kotto'),
      new State('Central African Republic', 'Haute-Kotto'),
      new State('Central African Republic', 'Haut-Mbomou'),
      new State('Central African Republic', 'Kemo'),
      new State('Central African Republic', 'Lobaye'),
      new State('Central African Republic', 'Mambere-Kadei'),
      new State('Central African Republic', 'Mbomou'),
      new State('Central African Republic', 'Nana-Grebizi'),
      new State('Central African Republic', 'Nana-Mambere'),
      new State('Central African Republic', 'Ombella-Mpoko'),
      new State('Central African Republic', 'Ouaka'),
      new State('Central African Republic', 'Ouham'),
      new State('Central African Republic', 'Ouham-Pende'),
      new State('Central African Republic', 'Sangha-Mbaere'),
      new State('Central African Republic', 'Vakaga'),

      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
      new State('Central African Republic', 'Vakaga'),
    ];
  }

}
